name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set version variable
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ledger
        version: 1.0
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

    - name: Set host triple
      run: |
        echo "host_triple=$(rustc -vV | grep host | cut -d' ' -f2)" >> "$GITHUB_ENV"
    - name: Compress the binary
      run: |
        tar -cvzf largo-rs-${RELEASE_VERSION}-${host_triple}.tar.gz target/release/largo-rs
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          largo-rs-${{ env.RELEASE_VERSION }}-${{ env.host_triple }}.tar.gz
